(() => {
  window.PROJECT_LIBRARY = [
    {
      id: 1,
      title: "PulseX Product Film",
      client: "NeonPix",
      year: 2025,
      category: "commercial",
      categoryLabel: "Commercial",
      format: "16:9 + 9:16",
      delivery: "Campaign Package",
      highlight: "3.8x CTR Lift",
      image: "https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b?auto=format&fit=crop&w=1200&q=80",
      description: "Fast-paced brand film and derivative ad cuts designed for paid social and landing-page hero placements.",
    },
    {
      id: 2,
      title: "Founders Unfiltered",
      client: "Kinetic Lab",
      year: 2024,
      category: "documentary",
      categoryLabel: "Documentary",
      format: "4K Master",
      delivery: "Episode + Trailer",
      highlight: "52 min final cut",
      image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=80",
      description: "Long-form founder documentary edited for narrative clarity, emotional pacing, and retention.",
    },
    {
      id: 3,
      title: "Sprint Reels Pack",
      client: "Atlas Creators",
      year: 2025,
      category: "social",
      categoryLabel: "Social",
      format: "9:16",
      delivery: "30 Reels / Month",
      highlight: "12.6M views",
      image: "https://images.unsplash.com/photo-1515378960530-7c0da6231fb1?auto=format&fit=crop&w=1200&q=80",
      description: "High-volume reel workflow with hook-first structures, subtitles, and branded motion overlays.",
    },
    {
      id: 4,
      title: "Echo Session Live",
      client: "Blueframe Records",
      year: 2024,
      category: "music",
      categoryLabel: "Music",
      format: "4K Performance",
      delivery: "MV + Teasers",
      highlight: "1.2M organic plays",
      image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80",
      description: "Performance edit with multi-cam sync, cinematic color treatment, and rhythmic transitions.",
    },
    {
      id: 5,
      title: "Launch Story 2.0",
      client: "Foundry Media",
      year: 2025,
      category: "commercial",
      categoryLabel: "Commercial",
      format: "16:9",
      delivery: "Master + Cutdowns",
      highlight: "Global rollout",
      image: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=1200&q=80",
      description: "Narrative-driven launch film with alternate openers and market-specific end cards.",
    },
    {
      id: 6,
      title: "Ground Report",
      client: "Ripple Studios",
      year: 2023,
      category: "documentary",
      categoryLabel: "Documentary",
      format: "24 fps",
      delivery: "Feature Segment",
      highlight: "Festival shortlist",
      image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
      description: "Documentary edit emphasizing interview cadence, archival weaving, and tonal continuity.",
    },
    {
      id: 7,
      title: "Neon Drift Visual Album",
      client: "Void Collective",
      year: 2025,
      category: "music",
      categoryLabel: "Music",
      format: "4K Widescreen",
      delivery: "Full Visual Album",
      highlight: "2.4M streams",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
      description: "Six-track visual album cut with a unified color language, abstract motion inserts, and immersive pacing.",
    },
    {
      id: 8,
      title: "Brand Lift Campaign",
      client: "Apex Digital",
      year: 2024,
      category: "commercial",
      categoryLabel: "Commercial",
      format: "16:9 + 1:1",
      delivery: "Multi-format Pack",
      highlight: "47% brand recall",
      image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80",
      description: "Cross-platform campaign with tailored aspect ratios, localized audio mixes, and A/B variant exports.",
    },
    {
      id: 9,
      title: "Urban Pulse Shortform",
      client: "Stride Social",
      year: 2025,
      category: "social",
      categoryLabel: "Social",
      format: "9:16",
      delivery: "Weekly Series",
      highlight: "800K avg reach",
      image: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=1200&q=80",
      description: "Ongoing weekly short-form series built around trending hooks, kinetic text overlays, and retention arcs.",
    },
    {
      id: 10,
      title: "The Quiet Makers",
      client: "Lens & Lore",
      year: 2023,
      category: "documentary",
      categoryLabel: "Documentary",
      format: "4K Cinema",
      delivery: "Short Film",
      highlight: "22-min runtime",
      image: "https://images.unsplash.com/photo-1532103054090-3491f1a05d0d?auto=format&fit=crop&w=1200&q=80",
      description: "Short documentary portrait of independent artisans — cut for emotional depth and slow-burn storytelling.",
    },
    {
      id: 11,
      title: "Velocity Apparel Drop",
      client: "Kore Brand",
      year: 2024,
      category: "commercial",
      categoryLabel: "Commercial",
      format: "16:9 + 9:16",
      delivery: "Product Launch Kit",
      highlight: "Sold out in 6 hrs",
      image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=80",
      description: "High-energy product reveal film timed to the collection drop, with teaser, hero, and story formats.",
    },
    {
      id: 12,
      title: "Frequency Live Set",
      client: "Pulse Audio",
      year: 2025,
      category: "music",
      categoryLabel: "Music",
      format: "4K Multi-cam",
      delivery: "Live Edit + Clips",
      highlight: "Top 3 trending",
      image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80",
      description: "Live set cut from 8-camera shoot — synced to BPM, graded for stage lighting, delivered in 48 hrs.",
    },
  ];
})();